export const bankProviders = [
  "Axis Bank Ltd.",
  "Bandhan Bank Ltd.",
  "Bank of Baroda",
  "Bank of India",
  "Bank of Maharashtra",
  "CSB Bank Ltd.",
  "Canara Bank",
  "Central Bank of India",
  "City Union Bank Ltd.",
  "DCB Bank Ltd.",
  "Dhanlaxmi Bank Ltd.",
  "Federal Bank Ltd.",
  "HDFC Bank Ltd",
  "ICICI Bank Ltd.",
  "IDBI Bank Ltd.",
  "IDFC First Bank Ltd.",
  "Indian Bank",
  "Indian Overseas Bank",
  "Induslnd Bank Ltd",
  "Jammu & Kashmir Bank Ltd.",
  "Karnataka Bank Ltd.",
  "Karur Vysya Bank Ltd.",
  "Kotak Mahindra Bank Ltd",
  "Nainital Bank Ltd.",
  "Others",
  "Punjab & Sind Bank",
  "Punjab National Bank",
  "RBL Bank Ltd.",
  "South Indian Bank Ltd.",
  "State Bank of India",
  "Tamilnad Mercantile Bank Ltd.",
  "UCO Bank",
  "Union Bank of India",
  "YES Bank Ltd.",
];

export const rupeeFormat = new Intl.NumberFormat("en-IN", {
  style: "currency",
  currency: "INR",
  maximumFractionDigits: 0,
});
